### PR TITLE
Possible fix for issue #275

### PR DESCRIPTION
**Pull request by hlaaftana**
I'm doing this online, so tell me if it works. This is attempting to fix https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/275

### CODE REVIEW

**Comment by elifoster** [comment]
On one hand I feel like this definitely could be the solution, but I also think it might not be. Do you have some way to test it?

**Comment by hlaaftana** [comment]
Unfortunately not. I'm on mobile.

**Comment by elifoster** [comment]
My computer can't handle severs and clients at the same time, so of you can confirm that this fixes it I'll merge. Or if someone like @xbony2 can confirm it...

**Comment by hlaaftana** [comment]
I'm on the computer now. Setting up the workspace took long, yet I was able to test. Could not reproduce the issue with the fix. Followed this: "if I am offline, and a rupture disk does rupture it causes the server to crash. "

**Pull request merged**
