### PR TITLE
Fixing squid: S1118 Utility classes should not have public constructors

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1118 - “Utility classes should not have public constructors ”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1118
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by xbony2** [comment]
This just wastes space. There's no reason to disable the instancing; nobody is making useless instances, since there is no reason to do so, so it is not an issue.

**Comment by devFozgul** [comment]
Hi, For many things in software development, one  may say "there is no need
to be so precise. My app works well without it!".  However, as software
engineers we should look for "Consistency, and Least Surprise"  in our
work; and that PR is just an example of that principle.
Thanks a lot.

**Comment by elifoster** [comment]
Right, but I'd say throwing a bunch of exceptions if you happen to make an instance of something actually increases the surprise factor of the project.

**Comment by devFozgul** [comment]
Hi,
I will change  it without throwing exceptions. I will add just a private
constructor. Is that OK?
Thank you.

**Comment by elifoster** [comment]
Is there any point in doing that? I read the squid rule thing, but it didn't seem to provide any reason for it.

**Comment by devFozgul** [comment]
Hi Eli, I would like to  make an agreement with you if you accept: I would
like to send you an example of my  each correction that  I wish to do
before attempting to fix the 'issue"  throughout the whole project. That
way I will  at least not  waste a big portion of my  time for fixes that
will not be accepted in the end for "subjective" reasons.
If you wish that I work on your project pf course. Please let me know if
you think otherwise. I will not go on working on your project.
Best regards,

**Comment by elifoster** [comment]
I'm fine with most of the changes you are making, there are just styling issues with a few of them, and, in this case, convoluted prs.

I'm confused. Are you going to continue fixing these squid issues in the project, or are you only going to fix those that I "accept"?

**Comment by devFozgul** [comment]
Well, of course I need some   approval.  I would like  to certainly
continue fixing the squid issues in your project  but I am afraid if most
of my efforts  will be in vain. We need to strike a certain amount of
approval in our work if this project  is to be continued by DevFactory.  I
hope you understand me.
Regards.

**Comment by elifoster** [comment]
Okay. So you're not going to then?

**Comment by devFozgul** [comment]
No I will continue to do, but please think twice before you refuse to merge
it:))

**Comment by elifoster** [comment]
That's why I asked what the purpose of this change was...

**Comment by devFozgul** [comment]
Ok. I will check it. Probably the rule title and the "content of the
fixing" got mixed up.

**Comment by elifoster** [comment]
No, I'm just not sure why you'd want to make this change.

**Comment by devFozgul** [comment]
Do you mean "adding default:break;"  within switch?

**Comment by devFozgul** [comment]
My reason for adding "default:break;" to the end of each switch block:
I am copying from my notes:
"

   1. Refactorability. If all your branches end with break or return, you
   can reorder them without changing the meaning. This makes it less likely
   for such a reordering to introduce a regression.
   2. Consistency, and Least Surprise. Consistency says your branches
   should end consistently, unless they are actually different in meaning. The
   Principle of Least Surprise dictates that similar things should look
   similar. Ending the last branch of a switch block exactly like the
   preceding ones fulfills both, which makes for easier reading and
   understanding. If you leave out the explicit break, the last branch will
   be optically different (which is especially important for quick scanning),
   and in order to see that it's really not different, the reader has to
   descend to the nitty-gritty level of reading individual statements.
   3. Protecting yourself. If you make a habit of ending all your
switch branches
   with a break, it will become automatic after a while, and you'll be less
   likely to accidentally forget it where it does matter. Training yourself to
   expect the break at the end of every branch also helps detecting missing
   break statements, which is great for debugging and troubleshooting."

**Comment by elifoster** [comment]
That is a different PR. This one is about private constructors.

**Comment by devFozgul** [comment]
Aha!  It is  for usage of the class without creating an object first. If
you do not add a private constructor, there is nothing preventing you from
creating an object for using the fields. Creating objects are costly and
since there is no need to create an object to access the fields, we are
just closing it for instantiation via placing a private constructor as the
rule says. I should have actually made the class "final" also. Because it
is not meant for sub-classing from either.

**Comment by elifoster** [comment]
Well, yeah, I just don't really understand what benefit we get out of locking that, because, as xbony2 said, nobody is doing that and nobody would do as their IDE would yell at them for it anyway.

**Comment by devFozgul** [comment]
Well, let me tell the Sonar team then so that they remove that rule from
their inventory:))

**Comment by xbony2** [comment]
It's sort of a flaw in Java itself that everything has to be class-oriented.

**Pull request closed without merging**
