### PR TITLE
GitHub templates

### PR DESCRIPTION
**Pull request by elifoster**
GitHub has finally implemented PR and issue templates. We should utilize this.

@xbony2 What do you think?

### CODE REVIEW

**Comment by xbony2** [comment]
And this means... what does it mean?

**Comment by Nincodedo** [comment]
Minor note, you can put Contributing.md and these two templates in a .github folder on the root of the repo and they will still work properly.

**Comment by Strikingwolf** [comment]
@xbony2 every issue and pull request will start with those files as their basis and thus users should see that certain things are needed.

**Comment by elifoster** [comment]
@Nincodedo I'm fine with them being in the root as there isn't any code there anyway, and I like to quickly get to the code style.

**Comment by elifoster** [comment]
@xbony2 Here's some info from GitHub: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by xbony2** [comment]
It's okay, but will it really be that effective? People who don't care that much will still ignore it.

**Comment by elifoster** [comment]
No clue. It's only been released a couple days ago.

**Comment by elifoster** [comment]
So... What are we doing with this?

**Comment by xbony2** [comment]
idc

**Comment by elifoster** [comment]
@xbony2 So am I free to merge, then?

**Comment by xbony2** [comment]
Can you find the Merge pull request button?

**Pull request merged**
