### PR TITLE
Changed filling water into boilers.

### PR DESCRIPTION
**Pull request by vidaj**
Boilers now support being filled by generic fluid containers containing
water. Added support for other mods to override which fluid is
considedered water.

### CODE REVIEW

**Comment by vidaj** [comment]
Not sure what style guide you follow, so I tried to mimic the style as close as possible. As much as I loathe static helper classes, this was the easiest way to reuse the same code in several places, and not change the current structure of the files.

**Comment by elifoster** [comment]
Looks good to me. You did a lot of other changes to style like using proper variable names, so thanks for that.

@xbony2 and @Strikingwolf Please review this.

:+1:

**Comment by elifoster** [comment]
@vidaj, didn't see your last comment.

>Not sure what style guide you follow, so I tried to mimic the style as close as possible.

We use a modified version of the Google style guide, as seen in [CONTRIBUTING.md](). You followed it pretty well.

>As much as I loathe static helper classes, this was the easiest way to reuse the same code in several places, and not change the current structure of the files.

Why do you loathe static helper classes?

**Comment by xbony2** [comment]
It's pretty good yo.

**Comment by elifoster** [comment]
>PR is fine

- @Strikingwolf 

Going to merge

**Comment by vidaj** [comment]
> Why do you loathe static helper classes?

It's not a big deal, but usually I feel that static helper classes is a symptom of a missing abstraction.

Glad to see I could help, though :)

**Pull request merged**
