### PR TITLE
squid: S2293 The diamond operator ("<>") should be used

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S2293 - “The diamond operator (""<>"") should be used ”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S2293
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by elifoster** [comment]
I'll merge if you remove the changes to codechicken lib

**Comment by devFozgul** [comment]
My next move will be to remove the changes from  codechicken/lib in  PRs like this one and send them to you again with fresh PRs. I will do them on Sunday. . There are 6 or 7 cases like that.

**Comment by elifoster** [comment]
You don't need to send new PRs. You can just remove the changes to codechicken lib in DevFactory:release/The_diamond_operator__should_be_used and squash the commits.

**Comment by devFozgul** [comment]
I am closing this PR.  I have made the required changes in a new PR. #444

**Pull request closed without merging**
