### PR TITLE
Crossmod refactor

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by elifoster** [comment]
@xbony2 Please make sure everything matches the style guide. I can see quite a few things that do not match it. Will reopen once that's done.

**Comment by xbony2** [comment]
I assume you speak of the "Braces are used where optional" thing. I regret agreeing to that part :P

**Comment by elifoster** [comment]
It's also the use of spaces. Spaces should be put in between () and {

**Comment by xbony2** [comment]
Bleah, at least you aren't one of those people who put the bracket on a new line.

**Comment by elifoster** [comment]
I really dislike doing that, and reading code where that is used.

**Comment by xbony2** [comment]
This closed #273 btw.

**Comment by xbony2** [comment]
(I'll refactor it later to the style requirements)

**Comment by xbony2** [comment]
Goddamn conflicts!

**Comment by xbony2** [comment]
Santa, you may have to fix these conflicts for me >.> using the git command-line makes me feel suicidal.

**Comment by elifoster** [comment]
Ok, ill do that once the pr matches the code  style

**Comment by xbony2** [comment]
Just to note what this PR does (for changelog stuff):
* Makes FSP interact with mods in a more direct way, making it easier to add future integration.
* Fixes bug #273 
* Adds CCC and NEI as dependencies to prepare for future integration.

**Comment by xbony2** [comment]
Everything should be good :)

**Comment by elifoster** [comment]
You fixed some of the styling. I'll just fix the rest once I get git and stuff installed on my gf's computer.

**Comment by elifoster** [comment]
God damn it. Don't pull that. Atom handles spaces and tabs stupidly, so I'll need to refix that.

**Comment by elifoster** [comment]
Sorry, Git is being an asshole and I have no idea what is going on.

**Comment by elifoster** [comment]
Okay, I'm going out for a bit. Everything is back to normal. I will get Atom working properly with spaces/tabs when I get back, or tomorrow, or something. Then, I'll fix some styling (assuming you don't while I'm gone), and get it ready to merge. Then merge. I will try to not ruin everything again. Te siento.

**Comment by elifoster** [comment]
This really, really needs to merge. I will actually fix the remaining style issues right now.

**Pull request merged**
