### PR TITLE
Release/string literals should not be duplicated part 1

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1192 - “String literals should not be duplicated”. 
This PR will reduce 80 min of TD.
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1192
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by devFozgul** [comment]
I tried to push the PR on branch 1.9. Please review it and let me know asap if that is what you wanted me to do.Thanks.

**Comment by elifoster** [comment]
Um... You added a ton of random commits.

**Comment by devFozgul** [comment]
I do not understand this. The previous commits I had done long before. They are not new. How come they appeared here, I need to find out. Perhaps a name similarity made my new commit appear under the other commits?

**Comment by elifoster** [comment]
No longer taking PRs to master.

**Pull request closed without merging**
